sudo: required
services:
  - docker
install:
  - docker compose up -d
# deploy:
#   provider: elasticbeanstalk
#   region: 'us-east-2'
#   app: 'docker-react'
#   env: 'DockerReact-env'
#   bucket_name: 'elasticbeanstalk-us-east-2-123456789'
#   bucket_path: 'docker-react'
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
